coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 1%
    patch: true
    changes: true

comment:
  behavior: default
  layout: "file,tree,flags"  # Corrected layout options
  show_carryforward_flags: false
